/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventanas;

/**
 *
 * @author Juan Manuel
 */
public class FinJuego extends javax.swing.JFrame {

    int fila;
    int columna;
    int bombas;
    int jugadores;

    public FinJuego(int bombas, int fila, int columna, int jugadores) {
        initComponents();
        this.columna = columna;
        this.fila = fila;
        this.bombas = bombas;
        this.jugadores = jugadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRepetir = new javax.swing.JButton();
        tbnInicio = new javax.swing.JButton();
        btnNuevoJuego = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("!HAS PERDIDO¡");

        btnRepetir.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnRepetir.setForeground(new java.awt.Color(0, 0, 0));
        btnRepetir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/repetir.png"))); // NOI18N
        btnRepetir.setText("REPETIR");
        btnRepetir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepetirActionPerformed(evt);
            }
        });

        tbnInicio.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tbnInicio.setForeground(new java.awt.Color(0, 0, 0));
        tbnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/inicio.png"))); // NOI18N
        tbnInicio.setText("INICIO");
        tbnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnInicioActionPerformed(evt);
            }
        });

        btnNuevoJuego.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        btnNuevoJuego.setForeground(new java.awt.Color(0, 0, 0));
        btnNuevoJuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new.png"))); // NOI18N
        btnNuevoJuego.setText("NUEVO JUEGO");
        btnNuevoJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoJuegoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnNuevoJuego)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tbnInicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRepetir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(btnRepetir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbnInicio)
                .addGap(18, 18, 18)
                .addComponent(btnNuevoJuego)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepetirActionPerformed
        if (jugadores == 1) {
            JuegoUnJugador jug = new JuegoUnJugador(bombas, fila, columna);
            jug.setVisible(true);
            jug.setLocationRelativeTo(this);
            this.dispose();
        }else{
        JuegoDosJugadores juge = new JuegoDosJugadores(bombas, fila, columna);
        juge.setVisible(true);
        juge.setLocationRelativeTo(this);
        this.dispose();
        }
    }//GEN-LAST:event_btnRepetirActionPerformed

    private void tbnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnInicioActionPerformed
        VentanaInicial ini = new VentanaInicial();
        ini.setVisible(true);
        ini.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_tbnInicioActionPerformed

    private void btnNuevoJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoJuegoActionPerformed
        LobbyJuego loby = new LobbyJuego();
        loby.setVisible(true);
        loby.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_btnNuevoJuegoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoJuego;
    private javax.swing.JButton btnRepetir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton tbnInicio;
    // End of variables declaration//GEN-END:variables
}
